const userData = [
    { "full_name": "Helen Akaji", "email": "helen.akaji@arndaleacademy.com" },
    { "full_name": "Mayos Favour", "email": "mayos.favour@arndaleacademy.com" },
    { "full_name": "Abdullahi Biliya", "email": "abdullahi.biliya@arndaleacademy.com" },
    { "full_name": "Grace Okewole", "email": "grace.okewole@arndaleacademy.com" },
    { "full_name": "Beatrice Harding", "email": "beatrice.harding@arndaleacademy.com" },
    { "full_name": "Blessing Nansak", "email": "blessing.nansak@arndaleacademy.com" },
    { "full_name": "Oluchi Okoronkwo", "email": "oluchi.okoronkwo@arndaleacademy.com" },
    { "full_name": "Omolowo Jacob", "email": "omolowo.jacob@arndaleacademy.com" },
    { "full_name": "Onyeka Obeleagu", "email": "onyeka.obeleagu@arndaleacademy.com" },
    { "full_name": "Ndifon Ihot Ogobi", "email": "ndifon.ihot.ogobi@arndaleacademy.com" },
    { "full_name": "Marvellous Olives", "email": "marvellous.olives@arndaleacademy.com" },
    { "full_name": "Oladunyoye Isaiah", "email": "oladunyoye.isaiah@arndaleacademy.com" },
    { "full_name": "Abdulkadir Dansidi", "email": "abdulkadir.dansidi@arndaleacademy.com" },
    { "full_name": "Abdullahi Adam", "email": "abdullahi.adam@arndaleacademy.com" },
    { "full_name": "Augusta Chidinma", "email": "augusta.chidinma@arndaleacademy.com" },
    { "full_name": "Ayim Patience", "email": "ayim.patience@arndaleacademy.com" },
    { "full_name": "Esther Reng", "email": "esther.reng@arndaleacademy.com" },
    { "full_name": "Eze Gift", "email": "eze.gift@arndaleacademy.com" },
    { "full_name": "Egbun Ibrahim", "email": "egbun.ibrahim@arndaleacademy.com" },
    { "full_name": "Nwachi Chiamaka", "email": "nwachi.chiamaka@arndaleacademy.com" },
    { "full_name": "Ntuenibok Ubong", "email": "ntuenibok.ubong@arndaleacademy.com" },
    { "full_name": "Aisha Habib", "email": "aisha.habib@arndaleacademy.com" },
    { "full_name": "Isah Yusuf", "email": "isah.yusuf@arndaleacademy.com" },
    { "full_name": "Imhoagene Success", "email": "imhoagene.success@arndaleacademy.com" },
    { "full_name": "Chukwuemeka Rachael", "email": "chukwuemeka.rachael@arndaleacademy.com" },
    { "full_name": "Ajayi Oluwaseyifunmi", "email": "ajayi.oluwaseyifunmi@arndaleacademy.com" },
    { "full_name": "Adeshina Qoreebullahi Gaata", "email": "adeshina.qoreebullahi.gaata@arndaleacademy.com" },
    { "full_name": "Uche Stephen Arinze", "email": "uche.stephen.arinze@arndaleacademy.com" },
    { "full_name": "Adeagbo Abdulsamad", "email": "adeagbo.abdulsamad@arndaleacademy.com" },
    { "full_name": "Olummaiye Olugbenga", "email": "olummaiye.olugbenga@arndaleacademy.com" },
    { "full_name": "Ukpabi Emmanuel Amaechi", "email": "ukpabi.emmanuel.amaechi@arndaleacademy.com" },
    { "full_name": "Eze Vincent Chijoke", "email": "eze.vincent.chijoke@arndaleacademy.com" },
    { "full_name": "Zakari Mohammed Ahmed", "email": "zakari.mohammed.ahmed@arndaleacademy.com" },
    { "full_name": "Safiya Abubakar Idris", "email": "safiya.abubakar.idris@arndaleacademy.com" }
];